/**
 * Generates the derived contract artifacts from the single source of truth
 * (Zod schemas in shared/src/contracts + the real engine):
 *
 *   shared/schemas/*.json   JSON Schema of every entity and message
 *   shared/fixtures/*.json  representative states captured from real matches
 *   shared/fixtures/index.ts typed access to the fixtures
 *
 *   npm run contract:generate          (re)write the files
 *   npm run contract:check             fail if they are out of date (CI)
 */
import './deterministic';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import * as contract from '@boucan/shared';
import { CLIENT_MESSAGES, makeError, PROTOCOL_VERSION, type ServerMessage } from '@boucan/shared';
import { DEFAULT_GAME_CONFIG } from '../src/config/game-config';
import { Harness, type TestClient } from '../test/harness';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../shared');
const check = process.argv.includes('--check');
const outputs = new Map<string, string>();

function emit(relative: string, data: unknown): void {
  outputs.set(relative, typeof data === 'string' ? data : `${JSON.stringify(data, null, 2)}\n`);
}

// ─── JSON Schemas ─────────────────────────────────────────────────────────────

const GENERATED_NOTE = 'GENERATED by `npm run contract:generate` from shared/src/contracts — do not edit.';

function schema(name: string, zod: z.ZodType, io: 'input' | 'output'): void {
  const json = z.toJSONSchema(zod, { unrepresentable: 'any', io }) as Record<string, unknown>;
  emit(`schemas/${name}.schema.json`, { ...json, title: name, $comment: GENERATED_NOTE });
}

const ENTITIES = [
  'Player',
  'Lobby',
  'MatchConfig',
  'MatchState',
  'MiniGameDefinition',
  'MiniGameSession',
  'MiniGameTiming',
  'PlayerResult',
  'ScoringSpec',
  'RoundEntry',
  'RoundResults',
  'Standing',
  'MatchResults',
  'RoomSnapshot',
  'ServerInfo',
  'ErrorPayload',
  'RoomEvent',
  'MiniGameStateMessage',
  'MiniGameEventMessage',
] as const;
for (const name of ENTITIES) schema(`model/${name}`, contract[name] as z.ZodType, 'output');
schema('messages/ClientEnvelope', contract.ClientEnvelope, 'input');
schema('messages/ServerMessage', contract.ServerMessage, 'output');
for (const [type, spec] of Object.entries(CLIENT_MESSAGES)) {
  schema(`messages/client/${type}.payload`, spec.payload, 'input');
  schema(`messages/client/${type}.reply`, spec.reply, 'output');
}

// ─── Fixtures from real matches ───────────────────────────────────────────────

interface SnapshotFixture {
  description: string;
  /** Player whose client this state was captured from. */
  you: string;
  snapshot: contract.RoomSnapshot;
}
const fixtureIndex: { key: string; file: string; kind: 'snapshot' | 'messages' | 'serverInfo' }[] = [];

function snapshotFixture(key: string, file: string, description: string, client: TestClient): void {
  const fixture: SnapshotFixture = { description, you: client.playerId!, snapshot: client.snapshot };
  contract.RoomSnapshot.parse(fixture.snapshot);
  emit(`fixtures/${file}.json`, fixture);
  fixtureIndex.push({ key, file, kind: 'snapshot' });
}

function messagesFixture(key: string, file: string, description: string, messages: unknown[]): void {
  for (const m of messages) contract.ServerMessage.parse((m as { message?: unknown }).message ?? m);
  emit(`fixtures/${file}.json`, { description, messages });
  fixtureIndex.push({ key, file, kind: 'messages' });
}

const realTimings = { config: { timings: DEFAULT_GAME_CONFIG.timings } };
const NAMES = ['Capitaine', 'Zoé', 'Momo', 'Lulu', 'Titouan', 'Inès', 'Sacha', 'Nour'];
// Example ids only: the character roster belongs to the frontend.
const CHARACTERS = ['fox', 'bull', 'cat', undefined, 'dog', 'chicken', undefined, 'rooster'];

// Scenario A — 8 players, full lobby, 5-round match with disconnections.
{
  const h = new Harness(realTimings);
  const host = h.client();
  const info = host.received.find((m) => m.type === 'reply')!;
  emit('fixtures/server-info.json', {
    description: 'Reply payload of `hello` (ServerInfo): limits, timings, minigame definitions.',
    serverInfo: contract.ServerInfo.parse((info as { payload: unknown }).payload),
  });
  fixtureIndex.push({ key: 'serverInfo', file: 'server-info', kind: 'serverInfo' });

  host.ok('room.create', { nickname: NAMES[0]!, characterId: CHARACTERS[0] });
  snapshotFixture('lobbyOnePlayer', 'lobby-1-player', 'Room just created: only the host, not ready.', host);

  const players = [host];
  for (let i = 1; i < 8; i++) {
    const c = h.client();
    c.ok('room.join', { code: host.snapshot.lobby.code, nickname: NAMES[i]!, characterId: CHARACTERS[i] });
    players.push(c);
    h.advance(400);
  }
  players.slice(0, 5).forEach((p) => p.ok('player.ready', { ready: true }));
  const dropper = players[6]!;
  const token = dropper.sessionToken!;
  dropper.close();
  h.advance(1_000);
  snapshotFixture(
    'lobbyEightPlayers',
    'lobby-8-players',
    'Full lobby: 8 players, 5 ready, one disconnected (seat kept during the grace period), some without character.',
    host,
  );

  const back = h.client();
  back.ok('room.resume', { sessionToken: token });
  players[6] = back;
  players.forEach((p, i) => i >= 5 && p.ok('player.ready', { ready: true }));
  host.ok('match.configure', { rounds: 5 });
  snapshotFixture('lobbyReady', 'lobby-ready', 'Everyone ready, host can start (lobby.canStart = true).', host);

  players.forEach((p, i) => p.autoplay(0.2 + (i % 5) * 0.2));
  host.ok('match.start');

  const seen = new Set<string>();
  const once = (key: string, fn: () => void) => {
    if (!seen.has(key)) {
      seen.add(key);
      fn();
    }
  };
  const authorityFixture: Record<string, string> = {
    local: 'minigameActiveLocal',
    server: 'minigameActiveServer',
    relay: 'minigameActiveRelay',
  };
  const quitter = players[3]!;
  const leaver = players[5]!;
  while (host.phase !== 'MATCH_RESULTS') {
    h.advance(h.tickMs);
    const snap = host.snapshot;
    const phase = snap.match.phase;
    const round = snap.match.round;
    if (round === 1) {
      const files: Record<string, [string, string, string]> = {
        MATCH_STARTING: ['matchStarting', 'match-starting', 'Match accepted, short intro before round 1.'],
        MINIGAME_PREPARING: ['minigamePreparing', 'minigame-preparing', 'Minigame announced (id, seed, params, participants); clients load then send minigame.ready.'],
        MINIGAME_COUNTDOWN: ['minigameCountdown', 'minigame-countdown', 'Countdown: timing.activeAt / endsAt are known, animate locally.'],
        MINIGAME_ENDING: ['minigameEnding', 'minigame-ending', 'Time is up (or everyone finished): waiting for last reports.'],
        MINIGAME_RESULTS: ['minigameResults', 'minigame-results', 'Round results (lastRound) and updated standings.'],
        INTERMISSION: ['intermission', 'intermission', 'Between two rounds: standings with previousRank / delta.'],
      };
      const f = files[phase];
      if (f) once(phase, () => snapshotFixture(f[0], f[1], f[2], host));
    }
    if (phase === 'MATCH_STARTING') once('MATCH_STARTING', () => snapshotFixture('matchStarting', 'match-starting', 'Match accepted, short intro before round 1.', host));
    if (phase === 'MINIGAME_ACTIVE' && snap.match.minigame) {
      const authority = snap.match.minigame.authority;
      const since = h.now - snap.match.phaseStartedAt;
      if (since >= 2_000) {
        once(`active-${authority}`, () =>
          snapshotFixture(
            authorityFixture[authority]!,
            `minigame-active-${authority}`,
            `Minigame running (authority "${authority}": ${
              authority === 'local' ? 'clients simulate and report' : authority === 'relay' ? 'clients stream progress, server relays shared state' : 'server judges'
            }).`,
            host,
          ),
        );
      }
      if (round === 2 && quitter.isOpen && since >= 1_000) quitter.close();
    }
    if (round === 2 && phase === 'MINIGAME_RESULTS') {
      once('disconnected', () =>
        snapshotFixture('playerDisconnected', 'player-disconnected', 'A player lost connection during a minigame: connection = "disconnected", dnf for this round, may resume.', host),
      );
    }
    if (round === 3 && phase === 'MINIGAME_PREPARING') {
      once('left', () => {
        leaver.ok('room.leave');
        snapshotFixture('playerLeft', 'player-left', 'A player left mid-match: connection = "left", kept in standings until back in the lobby.', host);
      });
    }
  }
  snapshotFixture('matchResults', 'match-results', 'Final ranking (match.final): standings, winners, every round. Host sends match.returnToLobby.', host);

  // Distinct semantic events seen during the match.
  const firstOf = new Map<string, ServerMessage>();
  for (const m of host.received) {
    if (m.type === 'room.event' && !firstOf.has(`room:${m.payload.kind}`)) firstOf.set(`room:${m.payload.kind}`, m);
    if (m.type === 'minigame.event' && !firstOf.has(`mg:${m.payload.event.type}`)) firstOf.set(`mg:${m.payload.event.type}`, m);
    if (m.type === 'minigame.state' && !firstOf.has('state')) firstOf.set('state', m);
  }
  messagesFixture('events', 'events', 'One example of each room.event kind, minigame.event type and minigame.state seen in a real match.', [...firstOf.values()]);

  // Error replies.
  const errors: ServerMessage[] = [];
  const probe = h.client();
  const collect = (reply: ServerMessage) => errors.push(reply);
  collect(probe.request('room.join', { code: 'ZZZZ', nickname: 'Perdu' }));
  collect(probe.request('room.create', { nickname: 'x' }));
  collect(probe.request('room.create', { nickname: 'C0nn4rd' }));
  collect(probe.request('player.ready', { ready: 'oui' as unknown as boolean }));
  collect(probe.request('player.ready', { ready: true }));
  probe.ok('room.create', { nickname: 'Sonde' });
  collect(probe.request('match.configure', { minigamePool: ['inconnu'] }));
  collect(probe.request('minigame.report', { sessionId: 'm_old.r1', result: { outcome: 'success' } }));
  const outdated = h.client({ handshake: false });
  collect(outdated.request('hello', { protocolVersion: PROTOCOL_VERSION + 1 }));
  errors.push({ type: 'reply', rid: 'r42', ok: false, error: makeError('RATE_LIMITED') });
  errors.push({ type: 'reply', rid: 'r43', ok: false, error: makeError('INTERNAL') });
  errors.push({ type: 'error', payload: { ...makeError('BAD_MESSAGE', { reason: 'invalidJson' }) } });
  errors.push({ type: 'session.ended', payload: { reason: 'kicked' } });
  messagesFixture('errors', 'errors', 'Typical refusals: `category` tells whose problem it is (protocol = client adapter bug, request = game rule, rate, server = backend bug).', errors);
  h.dispose();
}

// Scenario B — full message log of a 2-player, 3-round match (one minigame per authority).
{
  const h = new Harness({ config: { timings: DEFAULT_GAME_CONFIG.timings } });
  const a = h.client();
  a.ok('room.create', { nickname: 'Zoé', characterId: 'fox', config: { rounds: 3, minigamePool: ['interro-surprise', 'sonnerie', 'course-couloir'] } });
  const b = h.client();
  b.ok('room.join', { code: a.snapshot.lobby.code, nickname: 'Momo' });
  [a, b].forEach((p) => p.autoplay(0.7).ok('player.ready', { ready: true }));
  const start = h.now;
  const from = a.received.length;
  a.ok('match.start');
  h.advanceUntil(() => a.phase === 'MATCH_RESULTS', 600_000);
  a.ok('match.returnToLobby');
  // Timestamps are rebased on the match start so a mock can replay the log at any time.
  const log = a.received.slice(from).flatMap((message, idx) =>
    message.type === 'reply' ? [] : [{ t: a.receivedAt[from + idx]! - start, message }],
  );
  messagesFixture(
    'matchLog',
    'match-log-2p-3rounds',
    'Every message received by one client during a 2-player, 3-round match (local, server and relay minigames), from match.start to the return to the lobby. `t` = ms since match.start.',
    log,
  );
  h.dispose();
}

// ─── Fixture index ────────────────────────────────────────────────────────────

const kinds = { snapshot: 'SnapshotFixture', messages: 'MessagesFixture', serverInfo: 'ServerInfoFixture' };
const unique = [...new Map(fixtureIndex.map((f) => [f.key, f])).values()];
emit(
  'fixtures/index.ts',
  `// ${GENERATED_NOTE}
import type { RoomSnapshot, ServerInfo, ServerMessage } from '../src';
${unique.map((f) => `import ${f.key} from './${f.file}.json';`).join('\n')}

export interface SnapshotFixture {
  description: string;
  /** Player whose client this state was captured from. */
  you: string;
  snapshot: RoomSnapshot;
}
export interface MessagesFixture {
  description: string;
  messages: (ServerMessage | { t: number; message: ServerMessage })[];
}
export interface ServerInfoFixture {
  description: string;
  serverInfo: ServerInfo;
}

/** Representative data captured from real matches (see shared/fixtures/README.md). */
export const FIXTURES = {
${unique.map((f) => `  ${f.key}: ${f.key} as unknown as ${kinds[f.kind]},`).join('\n')}
};
export type FixtureName = keyof typeof FIXTURES;
`,
);

// ─── Write or check ───────────────────────────────────────────────────────────

const stale: string[] = [];
for (const [relative, content] of outputs) {
  const path = join(root, relative);
  let current: string | null = null;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    current = null;
  }
  if (current === content) continue;
  stale.push(relative);
  if (!check) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
}
// Remove generated files that no longer exist in the contract.
for (const dir of ['schemas/model', 'schemas/messages', 'schemas/messages/client']) {
  let files: string[] = [];
  try {
    files = readdirSync(join(root, dir)).filter((f) => f.endsWith('.json'));
  } catch {
    continue;
  }
  for (const f of files) {
    const rel = `${dir}/${f}`;
    if (!outputs.has(rel)) {
      stale.push(`${rel} (obsolete)`);
      if (!check) rmSync(join(root, rel));
    }
  }
}

if (check) {
  if (stale.length > 0) {
    console.error(`Contract artifacts are out of date (${stale.length}):\n  ${stale.join('\n  ')}\nRun: npm run contract:generate`);
    process.exit(1);
  }
  console.log(`Contract artifacts up to date (${outputs.size} files).`);
} else {
  console.log(`Generated ${outputs.size} files (${stale.length} changed) in shared/.`);
}
