// GENERATED by `npm run contract:generate` from shared/src/contracts — do not edit.
import type { RoomSnapshot, ServerInfo, ServerMessage } from '../src';
import serverInfo from './server-info.json';
import lobbyOnePlayer from './lobby-1-player.json';
import lobbyEightPlayers from './lobby-8-players.json';
import lobbyReady from './lobby-ready.json';
import matchStarting from './match-starting.json';
import minigamePreparing from './minigame-preparing.json';
import minigameCountdown from './minigame-countdown.json';
import minigameActiveRelay from './minigame-active-relay.json';
import minigameEnding from './minigame-ending.json';
import minigameResults from './minigame-results.json';
import intermission from './intermission.json';
import minigameActiveLocal from './minigame-active-local.json';
import playerDisconnected from './player-disconnected.json';
import playerLeft from './player-left.json';
import minigameActiveServer from './minigame-active-server.json';
import matchResults from './match-results.json';
import events from './events.json';
import errors from './errors.json';
import matchLog from './match-log-2p-3rounds.json';

export interface SnapshotFixture {
  description: string;
  /** Player whose client this state was captured from. */
  you: string;
  snapshot: RoomSnapshot;
}
export interface MessagesFixture {
  description: string;
  messages: (ServerMessage | { t: number; message: ServerMessage })[];
}
export interface ServerInfoFixture {
  description: string;
  serverInfo: ServerInfo;
}

/** Representative data captured from real matches (see shared/fixtures/README.md). */
export const FIXTURES = {
  serverInfo: serverInfo as unknown as ServerInfoFixture,
  lobbyOnePlayer: lobbyOnePlayer as unknown as SnapshotFixture,
  lobbyEightPlayers: lobbyEightPlayers as unknown as SnapshotFixture,
  lobbyReady: lobbyReady as unknown as SnapshotFixture,
  matchStarting: matchStarting as unknown as SnapshotFixture,
  minigamePreparing: minigamePreparing as unknown as SnapshotFixture,
  minigameCountdown: minigameCountdown as unknown as SnapshotFixture,
  minigameActiveRelay: minigameActiveRelay as unknown as SnapshotFixture,
  minigameEnding: minigameEnding as unknown as SnapshotFixture,
  minigameResults: minigameResults as unknown as SnapshotFixture,
  intermission: intermission as unknown as SnapshotFixture,
  minigameActiveLocal: minigameActiveLocal as unknown as SnapshotFixture,
  playerDisconnected: playerDisconnected as unknown as SnapshotFixture,
  playerLeft: playerLeft as unknown as SnapshotFixture,
  minigameActiveServer: minigameActiveServer as unknown as SnapshotFixture,
  matchResults: matchResults as unknown as SnapshotFixture,
  events: events as unknown as MessagesFixture,
  errors: errors as unknown as MessagesFixture,
  matchLog: matchLog as unknown as MessagesFixture,
};
export type FixtureName = keyof typeof FIXTURES;
